<header>
        <nav>
            <a class="logo" href="#">Afford My Baby</a>
            <div class="mainNav">
               <ul>
                <li><a class="navlinks" href="pages/shop.html">Shop!</a>
                  <ul class="dropdown">
                     <li><a href="pages/shop/clothing.html">Clothing & Acessories</a></li><br>
                     <li><a href="pages/shop/gear.html">Baby Gear</a></li><br>
                     <li><a href="pages/shop/diapering.html">Diapering</a></li><br>
                     <li><a href="pages/shop/feeding.html">Feeding</a></li><br>
                     <li><a href="pages/shop/bathing.html">Baby Bathing</a></li><br>
                     <li><a href="pages/shop/nursery.html">Nursery</a></li><br>
                     <li><a href="pages/shop/toys.html">Baby Toys</a></li><br>
                     <li><a href="pages/shop/health.html">Health & Safety</a></li><br>
                  </ul>
                </li>
                <li><a class="navlinks" href="pages/share.html">Share</a></li>
                <li><a class="navlinks" href="php/login_form.php">Login/Join</a></li>
                <li><a class="navlinks" href="pages/about.html">About</a></li>
                <li><a class="navlinks" href="pages/contact.html">Contact</a></li>
               </ul>
            </div>
        </nav>
    </header>

      <ul class="bxslider">
	    <li class="slide"><a href="pages/deals/deal1.html"><img title="Pack-n-Play $99.99" src="images/img1.jpg" /></a></li>
	    <li class="slide"><img title="Save now! 25% Off Essentials" src="images/img2.jpg" /></li>
	    <li class="slide"><img title="Pink Baby Bouncer 25% Off" src="images/img3.jpg" /></li>
	    <li class="slide"><img title="Jump-A-Roo! $59.99" src="images/img4.jpg" /></li>

      </ul>

    <hr>
   <div class="main">
    <div class="left">
    <article>
      <div class="date">
         <span class="month">Oct</span><br>
         <span class="day">12</span>
      </div>
        <h2>Baby Activity Mat</h2>
            <h3>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
tincidunt ut laoreet dolore magna aliquam erat volutpat</h3>
               <img class="item" width="200" height="200">
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim t, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat null</p>
    </article>
    
          <article>
      <div class="date">
         <span class="month">Oct</span><br>
         <span class="day">12</span>
      </div>
        <h2>Baby Activity Mat</h2>                    
            <h3>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
tincidunt ut laoreet dolore magna aliquam erat volutpat</h3>
               <img class="item" width="200" height="200">
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim t, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat null</p>
    </article>
    </div>
   <div class="right">
    <aside class="search">
         <div id="tfheader">
		<form id="tfnewsearch" method="get" action="http://www.google.com">
		        <input type="text" id="tfq" class="tftextinput4" name="q" size="18" maxlength="120"><input type="submit" value=" " class="tfbutton4">
		</form>
		<div class="tfclear"></div>
	</div>
        <p>Search Deals!</p>
    </aside>
    
    <aside class="links">
        <h3>Reasons to join!</h3>
            <ul>
                <li>Access to:</li><br>
                <li>Members only forum</li><br>
                <li>Personalized deals page</li><br>
                <li>Email deals before everyone else</li><br>
                <li><a href="pages/join.html">Join Today!</a></li>
            </ul>
    </aside>
   </div>
   <div class="clear"></div>
   </div>