<footer>
        <p>
            All Rights Reserved. Copyright 2014 Linkda Media.
        </p>
            <nav>
            <a class="logo" href=#>Afford My Baby</a>
            <div class="mainNav">
                <a class="navlinks" href="pages/shop.html">Shop!</a>
                <a class="navlinks" href="pages/share.html">Share</a>
                <a class="navlinks" href="pages/login.html">Login/Join</a>
                <a class="navlinks" href="pages/about.html">About</a>
                <a class="navlinks" href="pages/contact.html">Contact</a>
            </div>
        </nav>
    </footer>           
    </div>
   
   
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.bxslider.min.js"></script>
    
    <script type="text/javascript">
        $(document).ready(function(){
                $('.bxslider').bxSlider({
                  minSlides: 3,
                  maxSlides: 3,
                  moveSlides: 1,
                  captions: true,
                  pager: false,
                  slideWidth: 250,
                  slideMargin: 10
                });
        });
    </script>
</body>
</html>
